# Generated by Django 4.2.16 on 2024-11-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_review_options_alter_tractor_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
