# Generated by Django 4.2.16 on 2024-11-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_tractor_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='images',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
